CREATE TABLE orders (
    id char(36) PRIMARY KEY,
    user_id char(36) NOT NULL,
    total DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES users(id),
    CHECK (status IN ('PENDING', 'SHIPPED', 'DELIVERED', 'CANCELED', 'REFUNDED', 'COMPLETED'))
);
